extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "tsconfig.eslint.json"

rules:
  "func-style":
    - "error"
    - "expression"
  "@typescript-eslint/explicit-module-boundary-types": "error"
  "@typescript-eslint/no-unused-vars":
    - "warn"
    - varsIgnorePattern: "^_"
      args: "none"
      ignoreRestSiblings: true

overrides:
  - files: ["src/**/*.ts"]
    env:
      node: true
    rules:
      no-debugger: "error"

  - files: ["example/**/*.js"]
    env:
      node: true
